name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11.0

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Lint with Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        poetry run flake8 . --count --max-complexity=10 --max-line-length=100 --statistics --exclude=old/,config.py

    # - name: Test with pytest
    #   run: |
    #     poetry run nose2 -v --pretty-assert
    #   env:
    #     MOSP_INSTANCE: ${{ secrets.MOSP_INSTANCE }}
    #     MOSP_TOKEN: ${{ secrets.MOSP_USER_TOKEN }}

    - name: Type check with Mypy
      run: |
        poetry run mypy .
